dependencies:
  - name: ccd
    version: ~4.0.0-rc.14
    repository: '@hmctspublic'
  - name: elasticsearch
    version: ~1.30.0
    repository: '@stable'
  - name: logstash
    version: ~2.1.0
    repository: '@hmctspublic'

 
