dependencies:
  - name: ccd
    version: ~0.5.0
    repository: '@hmcts'
  - name: elasticsearch
    version: ~1.17.0
    repository: '@stable'
  - name: logstash
    version: ~1.4.3
    repository: '@hmcts'
