dependencies:
  - name: ccd
    version: ~4.3.5
    repository: '@hmctspublic'
  - name: elasticsearch
    version: ~1.30.0
    repository: '@stable'
  - name: logstash
    version: ~2.4.1
    repository: '@hmctspublic'
