dependencies:
  - name: ccd
    version: ~3.0.4
    repository: '@hmctspublic'
  - name: elasticsearch
    version: ~1.17.0
    repository: '@stable'
  - name: logstash
    version: ~1.4.3
    repository: '@hmctspublic'
