name: chart-ccd-elasticsearch pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    ref: master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

jobs:
- job: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: ccd-elasticsearch
      chartReleaseName: chart-ccd-elasticsearch-ci-test
      chartNamespace: chart-tests-ccd
      helmInstallTimeout: "500"
      serviceConnection: "DCD-CFTAPPS-SBOX"
      registryServiceConnection: "azurerm-prod"
      aksResourceGroup: "sbox-01-rg"
      aksCluster: "sbox-01-aks"

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: ccd-elasticsearch
      chartReleaseName: chart-ccd-elasticsearch
      chartNamespace: chart-tests-ccd
      serviceConnection: "DCD-CFTAPPS-SBOX"
      registryServiceConnection: "azurerm-prod"
      aksResourceGroup: "sbox-01-rg"
      aksCluster: "sbox-01-aks"
